- name: create the rabbitmq repo
  ansible.builtin.copy:
    src: rabbitmq.repo
    dest: /etc/yum.repos.d/rabbitmq.repo
  
- name: install rabbitmq server
  ansible.builtin.package:
    name: rabbitmq-server
    state: present
- name: enable and start rabbitmq server
  ansible.builtin.service:
    name: rabbitmq-server
    state: started
    enabled: yes
- name: useradd and set permissions
  community.rabbitmq.rabbitmq_user:
    user: roboshop
    password: RoboShop@1
    permissions:
      - vhost: /
        configure_priv: .*
        read_priv: .*
        write_priv: .*
    state: present