- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: app-setup.yaml
   
- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejs.yaml
   

- name: mongo repo create
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongo.repo
- name: mongo client installation
  ansible.builtin.package:
    name: mongodb-mongosh
    state: present
- name: connect to mongodb catalogue
  ansible.builtin.command: mongosh {{ mogodb_host }} --quiet --eval "db.getMongo().getDBNames().indexOf('catalogue')"
  register: catalogue_output


- name: print the catalogue output
  ansible.builtin.debug:
    msg: "{{ catalogue_output }}"
- name: load products in to catalogue
  ansible.builtin.shell: mongosh --host {{ mogodb_host }} </app/db/master-data.js
  when: catalogue_output.stdout | int < 0







